import 'controller/frame59_controller.dart';import 'package:cspayapp_flutter/core/app_export.dart';import 'package:cspayapp_flutter/widgets/custom_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class Frame59Dialog extends StatelessWidget {Frame59Dialog(this.controller);

Frame59Controller controller;

@override Widget build(BuildContext context) { return Container(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: double.infinity, margin: getMargin(left: 16, top: 274, right: 15, bottom: 317), decoration: AppDecoration.outlineBlack9001412.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.start, children: [GestureDetector(onTap: () {onTapImgClose();}, child: Padding(padding: getPadding(left: 16, top: 16, right: 16), child: CommonImageView(svgPath: ImageConstant.imgClose, height: getSize(20.00), width: getSize(20.00)))), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 16, right: 16), child: Text("lbl104".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: AppStyle.txtDBHelvethaicaMonXRegBd24.copyWith()))), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 16, top: 4, right: 16), child: Text("msg77".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: AppStyle.txtDBHelvethaicaMonX55Regular20Gray600.copyWith()))), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 16, top: 24, right: 16, bottom: 24), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.max, children: [CustomButton(width: 148, text: "lbl3".tr, variant: ButtonVariant.OutlineGray400, fontStyle: ButtonFontStyle.DBHelvethaicaMonX55Regular20Gray900), CustomButton(width: 148, text: "lbl5".tr, variant: ButtonVariant.OutlineBlack900281_2, fontStyle: ButtonFontStyle.DBHelvethaicaMonX55Regular20Gray900)])))]))])); } 
onTapImgClose() { Get.back(); } 
 }
